### ISSUE TITLE
Error: Format error decoding Jpeg: Error parsing image. Illegal start bytes:8950

### ISSUE THREAD

**Issue by stepanjakl** [blopker/alic#5]
Hi, great tool you created there. Thanks a lot!

I'm encountering an issue with some JPEG files. The error message I receive is:

```
Error: Format error decoding Jpeg: Error parsing image. Illegal start bytes: 8950
```

I've attached one of the JPEG files that trigger this error for your reference.

[File 07-06-2024, 14 15 36.jpeg.zip](https://github.com/user-attachments/files/16425688/File.07-06-2024.14.15.36.jpeg.zip)

Any ideas on what could be causing this?

**Comment by blopker** [comment]
Hey! Thanks for the kind words. I took a look and the image in question is actually a png file. Changing the extension to png let's Alic optimize it without issue:

<img width="712" alt="image" src="https://github.com/user-attachments/assets/74d78da1-fd63-499a-9ddd-7e998f2e526a">

Maybe Alic should use a better way to detect image formats rather than file extension though...

**Comment by stepanjakl** [comment]
Ah, so that’s what the issue was. Thanks for the help!

It would be nice if the extension could automatically set the correct file extension or provide a modal with options like skipping or changing the extension.

**Comment by blopker** [comment]
Not sure if this is still an issue for you, but Alic will now try to detect the correct file format based on the contents and output the correct extension if possible.
